// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CreateRoom.proto

#ifndef PROTOBUF_CreateRoom_2eproto__INCLUDED
#define PROTOBUF_CreateRoom_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_CreateRoom_2eproto();
void protobuf_AssignDesc_CreateRoom_2eproto();
void protobuf_ShutdownFile_CreateRoom_2eproto();

class CSCreateRoomRequest;
class CSCreateRoomResponse;
class CSJoinRoomRequest;
class CSJoinRoomResponse;
class CSFightReadyRequest;
class CSFightReadyResponse;

// ===================================================================

class CSCreateRoomRequest : public ::google::protobuf::Message {
 public:
  CSCreateRoomRequest();
  virtual ~CSCreateRoomRequest();

  CSCreateRoomRequest(const CSCreateRoomRequest& from);

  inline CSCreateRoomRequest& operator=(const CSCreateRoomRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSCreateRoomRequest& default_instance();

  void Swap(CSCreateRoomRequest* other);

  // implements Message ----------------------------------------------

  CSCreateRoomRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSCreateRoomRequest& from);
  void MergeFrom(const CSCreateRoomRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CSCreateRoomRequest)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_CreateRoom_2eproto();
  friend void protobuf_AssignDesc_CreateRoom_2eproto();
  friend void protobuf_ShutdownFile_CreateRoom_2eproto();

  void InitAsDefaultInstance();
  static CSCreateRoomRequest* default_instance_;
};
// -------------------------------------------------------------------

class CSCreateRoomResponse : public ::google::protobuf::Message {
 public:
  CSCreateRoomResponse();
  virtual ~CSCreateRoomResponse();

  CSCreateRoomResponse(const CSCreateRoomResponse& from);

  inline CSCreateRoomResponse& operator=(const CSCreateRoomResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSCreateRoomResponse& default_instance();

  void Swap(CSCreateRoomResponse* other);

  // implements Message ----------------------------------------------

  CSCreateRoomResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSCreateRoomResponse& from);
  void MergeFrom(const CSCreateRoomResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CSCreateRoomResponse)
 private:
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_CreateRoom_2eproto();
  friend void protobuf_AssignDesc_CreateRoom_2eproto();
  friend void protobuf_ShutdownFile_CreateRoom_2eproto();

  void InitAsDefaultInstance();
  static CSCreateRoomResponse* default_instance_;
};
// -------------------------------------------------------------------

class CSJoinRoomRequest : public ::google::protobuf::Message {
 public:
  CSJoinRoomRequest();
  virtual ~CSJoinRoomRequest();

  CSJoinRoomRequest(const CSJoinRoomRequest& from);

  inline CSJoinRoomRequest& operator=(const CSJoinRoomRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSJoinRoomRequest& default_instance();

  void Swap(CSJoinRoomRequest* other);

  // implements Message ----------------------------------------------

  CSJoinRoomRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSJoinRoomRequest& from);
  void MergeFrom(const CSJoinRoomRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 uin = 1;
  inline bool has_uin() const;
  inline void clear_uin();
  static const int kUinFieldNumber = 1;
  inline ::google::protobuf::int32 uin() const;
  inline void set_uin(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CSJoinRoomRequest)
 private:
  inline void set_has_uin();
  inline void clear_has_uin();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 uin_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_CreateRoom_2eproto();
  friend void protobuf_AssignDesc_CreateRoom_2eproto();
  friend void protobuf_ShutdownFile_CreateRoom_2eproto();

  void InitAsDefaultInstance();
  static CSJoinRoomRequest* default_instance_;
};
// -------------------------------------------------------------------

class CSJoinRoomResponse : public ::google::protobuf::Message {
 public:
  CSJoinRoomResponse();
  virtual ~CSJoinRoomResponse();

  CSJoinRoomResponse(const CSJoinRoomResponse& from);

  inline CSJoinRoomResponse& operator=(const CSJoinRoomResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSJoinRoomResponse& default_instance();

  void Swap(CSJoinRoomResponse* other);

  // implements Message ----------------------------------------------

  CSJoinRoomResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSJoinRoomResponse& from);
  void MergeFrom(const CSJoinRoomResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CSJoinRoomResponse)
 private:
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_CreateRoom_2eproto();
  friend void protobuf_AssignDesc_CreateRoom_2eproto();
  friend void protobuf_ShutdownFile_CreateRoom_2eproto();

  void InitAsDefaultInstance();
  static CSJoinRoomResponse* default_instance_;
};
// -------------------------------------------------------------------

class CSFightReadyRequest : public ::google::protobuf::Message {
 public:
  CSFightReadyRequest();
  virtual ~CSFightReadyRequest();

  CSFightReadyRequest(const CSFightReadyRequest& from);

  inline CSFightReadyRequest& operator=(const CSFightReadyRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSFightReadyRequest& default_instance();

  void Swap(CSFightReadyRequest* other);

  // implements Message ----------------------------------------------

  CSFightReadyRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSFightReadyRequest& from);
  void MergeFrom(const CSFightReadyRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CSFightReadyRequest)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_CreateRoom_2eproto();
  friend void protobuf_AssignDesc_CreateRoom_2eproto();
  friend void protobuf_ShutdownFile_CreateRoom_2eproto();

  void InitAsDefaultInstance();
  static CSFightReadyRequest* default_instance_;
};
// -------------------------------------------------------------------

class CSFightReadyResponse : public ::google::protobuf::Message {
 public:
  CSFightReadyResponse();
  virtual ~CSFightReadyResponse();

  CSFightReadyResponse(const CSFightReadyResponse& from);

  inline CSFightReadyResponse& operator=(const CSFightReadyResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSFightReadyResponse& default_instance();

  void Swap(CSFightReadyResponse* other);

  // implements Message ----------------------------------------------

  CSFightReadyResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSFightReadyResponse& from);
  void MergeFrom(const CSFightReadyResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CSFightReadyResponse)
 private:
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_CreateRoom_2eproto();
  friend void protobuf_AssignDesc_CreateRoom_2eproto();
  friend void protobuf_ShutdownFile_CreateRoom_2eproto();

  void InitAsDefaultInstance();
  static CSFightReadyResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// CSCreateRoomRequest

// -------------------------------------------------------------------

// CSCreateRoomResponse

// optional int32 result = 1;
inline bool CSCreateRoomResponse::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSCreateRoomResponse::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CSCreateRoomResponse::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CSCreateRoomResponse::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 CSCreateRoomResponse::result() const {
  return result_;
}
inline void CSCreateRoomResponse::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// -------------------------------------------------------------------

// CSJoinRoomRequest

// optional int32 uin = 1;
inline bool CSJoinRoomRequest::has_uin() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSJoinRoomRequest::set_has_uin() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CSJoinRoomRequest::clear_has_uin() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CSJoinRoomRequest::clear_uin() {
  uin_ = 0;
  clear_has_uin();
}
inline ::google::protobuf::int32 CSJoinRoomRequest::uin() const {
  return uin_;
}
inline void CSJoinRoomRequest::set_uin(::google::protobuf::int32 value) {
  set_has_uin();
  uin_ = value;
}

// -------------------------------------------------------------------

// CSJoinRoomResponse

// optional int32 result = 1;
inline bool CSJoinRoomResponse::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSJoinRoomResponse::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CSJoinRoomResponse::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CSJoinRoomResponse::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 CSJoinRoomResponse::result() const {
  return result_;
}
inline void CSJoinRoomResponse::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// -------------------------------------------------------------------

// CSFightReadyRequest

// -------------------------------------------------------------------

// CSFightReadyResponse

// optional int32 result = 1;
inline bool CSFightReadyResponse::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSFightReadyResponse::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CSFightReadyResponse::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CSFightReadyResponse::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 CSFightReadyResponse::result() const {
  return result_;
}
inline void CSFightReadyResponse::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CreateRoom_2eproto__INCLUDED
